# netlify.toml

[build]
  publish = "." # مسیر انتشار فایل‌های وبسایت شما (جایی که index.html قرار دارد)
  functions = "netlify/functions" # مهم: مسیر صحیح پوشه توابع شما

[dev]
  functions = "netlify/functions" # مهم: مسیر صحیح برای توسعه لوکال
  port = 8888
