    # netlify.toml

    [build]
      publish = "."
      functions = "netlify/functions"

    [dev]
      functions = "netlify/functions"
      port = 8888

    # مهم: این بخش را اضافه کنید
    [[plugins]]
    package = "@netlify/plugin-functions-install-core"
    
